/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.User;
import DAO.connectDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Alunos
 */
public class TelaUser extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public TelaUser() {
        initComponents();
    }
    
    String operacaoAtivaGlobal = "Nenhum";

    public TelaUser(String operacaoAtiva){
        initComponents();
        operacaoAtivaGlobal = operacaoAtiva;
        
        String operacao = "Incluir";
        if (operacaoAtiva.equals(operacao)) {
            this.setAllVisible(true);
            labelId.setVisible(false);
            idCliente.setVisible(false);
        }
        
        operacao = "Alterar";
        String operacaoExcluir = "Excluir";
        if (operacaoAtiva.equals(operacao) || operacaoAtiva.equals(operacaoExcluir)) {
            this.setAllVisible(false);
            labelId.setVisible(true); 
            idCliente.setVisible(true);
            
            buttonCadastrar.setVisible(true);
            buttonCadastrar.setText("Pesquisar");
            buttonVoltar.setVisible(true);
        }
        
        
    }
    
    private void setAllVisible(Boolean visible){
        this.labelId.setVisible(visible);
        this.idCliente.setVisible(visible);
        this.labelNome.setVisible(visible);
        this.nomeCliente.setVisible(visible);
        this.labelEmail.setVisible(visible);
        this.emailUsuario.setVisible(visible);
        this.labelCelular.setVisible(visible);
        this.celularUsuario.setVisible(visible);
        this.labelSenha.setVisible(visible);
        this.senhaUsuario.setVisible(visible);
        this.labelConfirma.setVisible(visible);
        this.confirmaSenha.setVisible(visible);
        this.labelAtivo.setVisible(visible);
        this.ativoUsuario.setVisible(visible);
    }
    
    private void setAllEnabled(Boolean enabled){
        this.labelId.setEnabled(enabled);
        this.idCliente.setEnabled(enabled);
        this.labelNome.setEnabled(enabled);
        this.nomeCliente.setEnabled(enabled);
        this.labelEmail.setEnabled(enabled);
        this.emailUsuario.setEnabled(enabled);
        this.labelCelular.setEnabled(enabled);
        this.celularUsuario.setEnabled(enabled);
        this.labelSenha.setEnabled(enabled);
        this.senhaUsuario.setEnabled(enabled);
        this.labelConfirma.setEnabled(enabled);
        this.confirmaSenha.setEnabled(enabled);
        this.labelAtivo.setEnabled(enabled);
        this.ativoUsuario.setEnabled(enabled);
        this.buttonCadastrar.setEnabled(enabled);
        this.buttonVoltar.setEnabled(enabled);
    }
    
    User novoUsuario = new User();
    boolean senhasIguais = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelId = new javax.swing.JLabel();
        labelSenha = new javax.swing.JLabel();
        idCliente = new javax.swing.JTextField();
        labelConfirma = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        buttonCadastrar = new javax.swing.JToggleButton();
        senhaUsuario = new javax.swing.JPasswordField();
        confirmaSenha = new javax.swing.JPasswordField();
        buttonVoltar = new javax.swing.JButton();
        labelNome = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        emailUsuario = new javax.swing.JTextField();
        labelCelular = new javax.swing.JLabel();
        celularUsuario = new javax.swing.JTextField();
        labelAtivo = new javax.swing.JLabel();
        ativoUsuario = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelId.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelId.setText("ID do Usuario:");

        labelSenha.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelSenha.setText("Senha:");

        labelConfirma.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        labelConfirma.setText("Confirma Senha:");

        errorLabel.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        buttonCadastrar.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        buttonCadastrar.setText("Cadastrar");
        buttonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        senhaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                verificaSenha(evt);
            }
        });

        confirmaSenha.setToolTipText("");
        confirmaSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                verificaSenha(evt);
            }
        });

        buttonVoltar.setText("← Voltar");
        buttonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarTelaMenu(evt);
            }
        });

        labelNome.setText("Nome Completo:");

        labelEmail.setText("E-mail:");

        labelCelular.setText("Celular:");

        labelAtivo.setText("Ativo:");

        ativoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ativoUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 210, Short.MAX_VALUE)
                        .addComponent(buttonCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonVoltar)
                                .addGap(18, 18, 18)
                                .addComponent(labelId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCelular)
                                    .addComponent(labelSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelConfirma)
                                    .addComponent(labelAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ativoUsuario)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(senhaUsuario)
                                    .addComponent(confirmaSenha)
                                    .addComponent(emailUsuario)
                                    .addComponent(celularUsuario))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeCliente)
                        .addContainerGap())
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonVoltar)
                    .addComponent(labelId)
                    .addComponent(idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celularUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCelular))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelConfirma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ativoUsuario)
                    .addComponent(labelAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCadastrar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        if (senhasIguais == false) {
            JOptionPane.showMessageDialog(this, "As senhas precisam ser iguais");
        }
        try {
            this.novoUsuario.setNumConta(this.contaCliente.getText());
            this.novoUsuario.setNumAgencia(this.agenciaCliente.getText());
            this.novoUsuario.setSenha(new String(this.senhaUsuario.getPassword()));
            this.novoUsuario.setIdCli(Integer.parseInt(this.idCliente.getText()));
            
            connectDAO connDAO = new connectDAO();
            connDAO.connectDB();
            connDAO.insereRegistroJFBD(this.novoUsuario);

        } catch (IllegalArgumentException err) {        
            JOptionPane.showMessageDialog(this, err.getMessage());
            return;
        }

        JOptionPane.showMessageDialog(this, "Usuário Cadastrado!");
        
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cadastrarActionPerformed

    private void verificaSenha(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_verificaSenha
        String strSenha = new String(this.senhaUsuario.getPassword());
        String strConfirma = new String(this.confirmaSenha.getPassword());
        if (strSenha.equals(strConfirma) || strConfirma.equals("")) {
            this.errorLabel.setText("");
            this.senhasIguais = true;
        } else {
            this.errorLabel.setText("As senhas não conferem.");
            this.senhasIguais = false;
        }
    }//GEN-LAST:event_verificaSenha

    private void voltarTelaMenu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarTelaMenu
        TelaMenu telaMenu = new TelaMenu();
        telaMenu.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_voltarTelaMenu

    private void ativoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ativoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ativoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ativoUsuario;
    private javax.swing.JToggleButton buttonCadastrar;
    private javax.swing.JButton buttonVoltar;
    private javax.swing.JTextField celularUsuario;
    private javax.swing.JPasswordField confirmaSenha;
    private javax.swing.JTextField emailUsuario;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField idCliente;
    private javax.swing.JLabel labelAtivo;
    private javax.swing.JLabel labelCelular;
    private javax.swing.JLabel labelConfirma;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelId;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JTextField nomeCliente;
    private javax.swing.JPasswordField senhaUsuario;
    // End of variables declaration//GEN-END:variables
}
